apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-dpl
  namespace: prod
  labels:
    app: app2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
      - name: app2
        image: mzain/argo:v2
        ports:
        - containerPort: 80
