apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-dpl
  namespace: prod
  labels:
    app: app1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - name: app1
        image: mzain/argo:v1
        ports:
        - containerPort: 80
